### ISSUE TITLE
Initialize the database

### ISSUE THREAD

**Issue by MrPresidentWhite** [liuxueyang/DownloadWallpaper#5]
How to initialize the database?

![Screenshot_201](https://user-images.githubusercontent.com/38688739/69276472-d73d8580-0bde-11ea-9607-b46d42f9b353.png)

**Comment by liuxueyang** [comment]
In the project root directory, `cp config.sample.json config.json` and fill the file `config.json` with your database configuration.

**Comment by MrPresidentWhite** [comment]
thank you it worked...
